# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='highlighted',
            field=models.TextField(default=''),
        ),
    ]
